steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/schema-validator:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/schema-validator:latest'
      - '-f'
      - 'dockerfile'
      - '.'
    id: 'build-image'

  # Step 2: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/schema-validator:$COMMIT_SHA'
    id: 'push-image'
    waitFor: ['build-image']

  # Step 3: Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/schema-validator:latest'
    id: 'push-latest'
    waitFor: ['build-image']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'schema-validator'
      - '--image'
      - 'gcr.io/$PROJECT_ID/schema-validator:$COMMIT_SHA'
      - '--region'
      - 'northamerica-northeast2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'POSTGRES_DB=postgres,POSTGRES_USER=postgres,DB_PORT=5432'
    id: 'deploy-cloud-run'
    waitFor: ['push-image']

# Configure build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Build timeout (10 minutes)
timeout: '600s'

# Substitutions for variables
substitutions:
  _SERVICE_NAME: 'schema-validator'
  _REGION: 'northamerica-northeast2'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/schema-validator:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/schema-validator:latest'
