services:
  - type: web
    name: schema-validator-api
    env: python
    plan: free
    buildCommand: pip install poetry && poetry install --no-dev
    startCommand: poetry run uvicorn backend.main:APP --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DB_HOST
        value: postgres_db
      - key: POSTGRES_DB
        value: postgres
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: postgres
      - key: PYTHONPATH
        value: /opt/render/project/src 